// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_nIJi4gAifEv3W-9ILhs_ObcWinz5KUM',
    appId: '1:89104785301:web:9c8e35768a186c2061e09c',
    messagingSenderId: '89104785301',
    projectId: 'ams-quiz',
    authDomain: 'ams-quiz.firebaseapp.com',
    databaseURL: 'https://ams-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'ams-quiz.appspot.com',
    measurementId: 'G-7055EJP7T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqXX_lAUeC66rFYqk-z0h-SAfXndx1aQ',
    appId: '1:89104785301:android:05d4922a56b3188261e09c',
    messagingSenderId: '89104785301',
    projectId: 'ams-quiz',
    databaseURL: 'https://ams-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'ams-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-e7JTQVhe_VHkPt8nng2Id4HhTtcg9Q',
    appId: '1:89104785301:ios:bea97c506ccf17c361e09c',
    messagingSenderId: '89104785301',
    projectId: 'ams-quiz',
    databaseURL: 'https://ams-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'ams-quiz.appspot.com',
    iosBundleId: 'com.example.asmquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-e7JTQVhe_VHkPt8nng2Id4HhTtcg9Q',
    appId: '1:89104785301:ios:bea97c506ccf17c361e09c',
    messagingSenderId: '89104785301',
    projectId: 'ams-quiz',
    databaseURL: 'https://ams-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'ams-quiz.appspot.com',
    iosBundleId: 'com.example.asmquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_nIJi4gAifEv3W-9ILhs_ObcWinz5KUM',
    appId: '1:89104785301:web:665bc4ba7895820b61e09c',
    messagingSenderId: '89104785301',
    projectId: 'ams-quiz',
    authDomain: 'ams-quiz.firebaseapp.com',
    databaseURL: 'https://ams-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'ams-quiz.appspot.com',
    measurementId: 'G-PEW1YGDZKX',
  );
}
